/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-11-16 08:15:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.ejanton.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import com.xt.ssb.util.Constants;

public final class CustomerRecordEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/ejanton/customer/../../includeScript.jsp", Long.valueOf(1446121151261L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String context = request.getContextPath();
	//Long departId = (Long)request.getSession().getAttribute(Constants.session_dept_id);
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	Date d = new Date();
	String now_d = sdf.format(d);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* .selectbox{width:430px;height:220px;margin:auto;} \r\n");
      out.write("/* .selectbox div{float:left;} \r\n");
      out.write(" */.selectbox .select-bar{padding:0 20px;} \r\n");
      out.write(".selectbox .select-bar select{ \r\n");
      out.write("\twidth:150px;height:200px;border:1px #eee outset;padding:4px; \r\n");
      out.write("} \r\n");
      out.write(".selectbox .btn{width:50px; height:30px; margin-top:10px; cursor:pointer;} \r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write(".select_box{\r\n");
      out.write("\twidth: 455px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".select_box div{\r\n");
      out.write("float:left;\r\n");
      out.write("}\r\n");
      out.write(".select-bar{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".select_box select{\r\n");
      out.write("\twidth:200px;height:200px;\r\n");
      out.write("}\r\n");
      out.write(".btn-bar{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 25px 11px 0px 11px;\r\n");
      out.write("}\r\n");
      out.write(".btn-bar span{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-bottom:-7px; \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".btn-bar input{\r\n");
      out.write("margin-top:3px;\r\n");
      out.write("\twidth:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_simple{\r\n");
      out.write("border:1px solid #ddd;\r\n");
      out.write("background-color:#FFF;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/controls/controls.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/easyui-lang-zh_CN.js\"></script> \n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/controls/controls.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(context);
      out.write("/app/ejanton/history/styles/History.css\">\t<script src='js/CustomerRecordEdit.js'></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src='../../../js/formCheck.js'></script>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t<div id='center' data-options=\"region:'center',border:false\" style=\"width: 500px;\">\r\n");
      out.write("\t\t\t<div id='customerRecordFormPanel' title=\"客户信息\" style=\"width: 100%; font-size: 13px;\">\r\n");
      out.write("\t\t\t\t<form id=\"customerRecordForm\" class='edit-form' method=\"post\">\r\n");
      out.write("\t\t\t\t<input name=\"customerId\"id=\"customerId\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t<table cellspacing='10'>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"><font color=red>*</font>电话</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" id=\"nl_edit_phone\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id='phone' name=\"phone\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class='normal-input' style='width:198px;' type=\"text\" id=\"phoneShow\" maxlength=\"14\" onKeyUp=\"value=value.replace(/\\D/g,'')\" onafterpaste=\"value=value.replace(/\\D/g,'')\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"phoneShow\" class=\"validateMsg\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"><font color=red>*</font>姓名</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" id=\"nl_edit_name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"normal-input\" type=\"text\" style='width:198px;'  id='name' data-ssbtype='text' name=\"name\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\" class=\"validateMsg\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\">性别</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" id=\"nl_edit_sex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"man\" name=\"sex\" type=\"radio\" value=\"1\" checked=\"checked\"><label for=\"man\">男</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t&emsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"lady\" name=\"sex\" type=\"radio\" value=\"0\"><label for=\"lady\">女</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name='type_' id='type_0' value=\"0\" ><label for=\"type_0\">咨询</label> &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name='type_' id='type_1' value=\"1\"><label for=\"type_1\">预约</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"record_type_0\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"><font color=red>*</font>咨询方式</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input id='adviceType'\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"easyui-combobox\" name=\"adviceType\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-ssbtype='combobox'\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200,valueField:'dictValue',textField:'dictName',panelHeight:'auto',editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"adviceType\" class=\"validateMsg\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\">渠道来源</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input id='channelSource'\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"easyui-combobox\" name=\"channelSource\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-ssbtype='combobox'\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200,valueField:'dictValue',textField:'dictName',panelHeight:'auto',editable:false,onSelect:function(rec){setSourceName(rec)}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"channelSourceShow\" id = \"channelSourceShow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"normal-input\" id=\"query\" placeholder=\"选择关联活动\" \r\n");
      out.write("\t\t\t\t\t\t\t\tonkeydown=\"setTrack(event)\" style=\"padding:1px; margin-right: 5px;width: 200px;display: none\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input  type=\"hidden\" id=\"activeId\" data-ssbtype=\"int\" name=\"activeId\" >\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"height: 200px; line-height: 1px; display: inline-block;\">病种</span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"normal-input\" id=\"diseaseShow\" placeholder=\"搜索病种\" style=\"width:198px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"margin-left: 51px;height: 30px;width: 50px;\">已选择病种</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"select_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"select-bar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select multiple=\"multiple\" id=\"select1\" style='width:200px;border:1px solid #ddd;border-top:0px solid #ddd;'> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-bar\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"add\"><input type=\"button\" class=\"btn_simple\" value=\">\"/></span><br /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"add_all\"><input type=\"button\" class=\"btn_simple\" value=\">>\"/></span><br /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"remove\"><input type=\"button\" class=\"btn_simple\" value=\"<\"/></span><br /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"remove_all\"><input type=\"button\" class=\"btn_simple\" value=\"<<\"/></span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"select-bar\"><select multiple=\"multiple\" id=\"select2\" style='border:1px solid #ddd;'></select></div> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\">常用病种</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td id=\"commonDis\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"record_type_1\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"><font color=red>*</font>预约时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-datetimebox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid='appointmentDate' data-ssbtype='date' name=\"appointmentDate\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false\" value=\"");
      out.print( now_d);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"appointmentDate\" class=\"validateMsg\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"record_type_1\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"><font color=red>*</font>预约科室</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\" easyui-combobox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid='appointmentOrg' data-ssbtype='combobox'\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"appointmentOrg\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200,valueField:'orgId',textField:'name',onSelect:function(res){initDoc(res)},editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"appointmentOrgName\" id = \"appointmentOrgName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"appointmentOrg\" class=\"validateMsg\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"record_type_1\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"><font color=red>*</font>预约医生</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\" easyui-combobox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid='appointmentDoc' data-ssbtype='combobox'\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"appointmentDoc\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200,valueField:'employeeId',textField:'name',onSelect:function(rec){getDocName(rec)},editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"appointmentDocName\" id = \"appointmentDocName\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"record_type_1\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\">专家号</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"normal-input\" id=\"expertNumber\" disabled=\"disabled\" style=\"width:200px; \">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"record_type_1\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\"><font color=red>*</font>到诊时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\"easyui-datetimebox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid='checkTime' data-ssbtype='date' name=\"checkTime\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"checkTime\" class=\"validateMsg\"></label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' style=\"width:90px;\" style=\"\"><span style=\"display: block;height: 100px;\">记录内容</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid='rembo' data-ssbtype='text' name=\"rembo\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"multiline:true,height:100,width:464\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- <div data-options=\"region:'east',border:false\" style=\"width: 480px;\">\r\n");
      out.write("\t\t\t<div style='margin-top: 6px;' id='electronicHistoryGrid'></div>\r\n");
      out.write("\t\t</div> -->\r\n");
      out.write("\t\t<div data-options=\"region:'south',split:true,border:false\"\r\n");
      out.write("\t\t\tstyle=\"height: 40px;\">\r\n");
      out.write("\t\t\t<div class='edit-form-btn' style='float: right; margin-right: 5px;'>\r\n");
      out.write("\t\t\t\t<a id='cancelBtn' class=\"easyui-linkbutton oper\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-form-undo'\" onclick='cancel()'>取消</a><!--  <a\r\n");
      out.write("\t\t\t\t\tid='deleteBtn' class=\"easyui-linkbutton oper\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-form-dustbin'\"\r\n");
      out.write("\t\t\t\t\tonclick='deleteCustomerRecord()'>删除</a> --> <a id='addBtn'\r\n");
      out.write("\t\t\t\t\tclass=\"easyui-linkbutton oper\"\r\n");
      out.write("\t\t\t\t\tstyle='margin-left: 10px; margin-right: 10px;'\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-form-ok'\"\r\n");
      out.write("\t\t\t\t\tonclick='saveCustomerRecord()'>保存</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
