/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-11-20 08:03:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.ejanton.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import com.xt.privilege.empower.bussiness.EmpowerDS;
import com.xt.ssb.util.Constants;

public final class CustomerRecordSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/ejanton/customer/../../includeScript.jsp", Long.valueOf(1447697011984L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String context = request.getContextPath();
	//Long deptId = (Long)request.getSession().getAttribute(Constants.session_dept_id);
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	Date d = new Date();
	String now_d = sdf.format(d);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>客户记录查询</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var now_d = '");
      out.print(now_d);
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.q_input{\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
	//Long employeeIde = Long.parseLong(request.getSession().getAttribute(Constants.session_employee_id)+"");
	String operationSet = request.getAttribute("operations")==null?"-1":request.getAttribute("operations").toString();
	
	//String uri = //获取当前页的url
			//截取app 后面的 发到后台 获取操作资源的 identityName   print

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t\tvar operationSet = \"");
      out.print(operationSet);
      out.write("\";\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/controls/controls.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/easyui-lang-zh_CN.js\"></script> \n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/controls/controls.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src='js/CustomerRecordSearch.js'></script>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id='center' class='search_main'\r\n");
      out.write("\t\t\tdata-options=\"region:'center',border:false\">\r\n");
      out.write("\t\r\n");
      out.write("\t<form id=\"customerRecordForm\" class='search-form' method=\"post\">\r\n");
      out.write("\t\t<table cellpadding=\"10\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table id=\"customerRecordTable\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>查询患者</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"normal-input q_input\" id=\"query\" placeholder=\"请输入患者姓名、手机号码\"  style=\"width: 99%\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"name\" name=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"customerId\" name=\"customerId\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td class='td-label advice_time' align='right' >\r\n");
      out.write("\t\t\t\t\t\t\t\t咨询时间\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class='advice_time' colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id='createDate' value='1' data-ssbtype='dateRange' name=\"createDate\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-datebox\" type=\"text\" id='createDateStart' data-ssbtype='date'data-options=\"width:98,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false,onSelect:function(rec){setSearchTime(rec,this)}\">\r\n");
      out.write("\t\t\t\t\t\t\t \t- \r\n");
      out.write("\t\t\t\t\t\t\t \t<input class=\"easyui-datebox\" type=\"text\" id='createDateEnd' data-ssbtype='date'  data-options=\"width:98,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false,onSelect:function(rec){setSearchTime(rec,this)}\" >\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class='td-label appointment_time' align='right' >\r\n");
      out.write("\t\t\t\t\t\t\t\t预约时间\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class='appointment_time' colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id='appointmentDate' value='1' data-ssbtype='dateRange' name=\"appointmentDate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-datebox\" type=\"text\" id='appointmentDateStart' data-ssbtype='date'  \r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"width:98,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false,onSelect:function(rec){setSearchTime(rec,this)}\" value=\"");
      out.print(now_d);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t \t- \r\n");
      out.write("\t\t\t\t\t\t\t \t<input class=\"easyui-datebox\" type=\"text\" id='appointmentDateEnd' \r\n");
      out.write("\t\t\t\t\t\t\t \tdata-ssbtype='date' data-options=\"width:98,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false,onSelect:function(rec){setSearchTime(rec,this)}\" value=\"");
      out.print(now_d);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class='td-label check_time' align='right' >\r\n");
      out.write("\t\t\t\t\t\t\t\t到诊时间\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"check_time\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=checkTime value='1' data-ssbtype='dateRange' name=\"checkTime\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-datebox\" type=\"text\" id='checkTimeStart' data-ssbtype='date' data-options=\"width:98,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false,onSelect:function(rec){setSearchTime(rec,this)}\">\r\n");
      out.write("\t\t\t\t\t\t\t \t- \r\n");
      out.write("\t\t\t\t\t\t\t \t<input class=\"easyui-datebox\" type=\"text\" id='checkTimeEnd' data-ssbtype='date' data-options=\"width:98,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false,onSelect:function(rec){setSearchTime(rec,this)}\" >\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<td class=\"check_time\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=checkTime value='1' data-ssbtype='dateRange' name=\"checkTime\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-datebox\" type=\"text\" id='checkTimeStart' data-ssbtype='date' data-options=\"width:100,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t \t- \r\n");
      out.write("\t\t\t\t\t\t\t \t<input class=\"easyui-datebox\" type=\"text\" id='checkTimeEnd' data-ssbtype='date' data-options=\"width:100,formatter:tcCoreformatter,parser:tcCoreParser,height:30,editable:false\" >\r\n");
      out.write("\t\t\t\t\t\t\t</td> -->\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>\r\n");
      out.write("\t\t\t\t\t\t\t\t渠道来源\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\" easyui-combobox\"  data-ssbtype='combobox' type=\"text\" id=\"channelSource\" name=\"channelSource\" data-options=\"height:30,width:201,valueField:'dictValue',textField:'dictName',editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label org_h'>\r\n");
      out.write("\t\t\t\t\t\t\t\t预约科室\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"org_h\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\" easyui-combobox\" type=\"text\" data-ssbtype='combobox' id=\"appointmentOrg\" name=\"appointmentOrg\" data-options=\"height:30,width:201,valueField:'orgId',textField:'name',editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>\r\n");
      out.write("\t\t\t\t\t\t\t\t咨询病种\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\" easyui-combobox\" data-ssbtype='combobox' type=\"text\" id=\"disease\" name=\"diseaseId\" data-options=\"height:30,width:206,valueField:'diseaseId',textField:'diseaseName',editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td align='left' vAlign='bottom' style='width: 260px;'>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton search\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-form-search-btn'\" id=\"resetBtn\"\r\n");
      out.write("\t\t\t\t\tonclick='resetQuery()'>重置</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"queryDataBtn\"\r\n");
      out.write("\t\t\t\t\tclass=\"easyui-linkbutton search\" style='margin-left:10px;display: none'\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-form-search-btn'\"\r\n");
      out.write("\t\t\t\t\tonclick='queryCustomerRecord()'>查询</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<div id='operbtn' class='operbtn'>\r\n");
      out.write("\t\t<a id=\"addDataBtn\" href=\"#\" class=\"easyui-linkbutton\" style=\"display: none\" onclick=\"addData()\">新增</a> \r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" id=\"deleteDataBtn\" onclick=\"deleteDataBtnClick()\">删除</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" id=\"editDataBtn\" onclick=\"editDataBtnClick()\">修改</a>\r\n");
      out.write("\t\t<a id=\"printDataBtn\" style=\"display: none\" href=\"#\" class=\"easyui-linkbutton\" onclick=\"print()\">打印</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"totalDiv\" style=\"text-align:right;display: inline-block;position: absolute;right: 0;font-size: 14px;z-index: 9999;\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"todayTitle\">今日新增预约:</td><td><span id=\"todayCount\" name=\"todayCount\" style=\"width: 50px;display: inline-block;text-align: left;\"></td>\r\n");
      out.write("\t\t\t\t\t<td id=\"yesterDayTitle\">昨日新增预约:</td><td><span id=\"yesterdayCount\" name=\"yesterdayCount\" style=\"width: 50px;display: inline-block;text-align: left;\"></td>\r\n");
      out.write("\t\t\t\t\t<td id=\"monthTitle\">本月预约:</td><td><span id=\"monthCount\"  name=\"monthCount\" style=\"width: 50px;display: inline-block;text-align: left;\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"examine\" >到诊率:</td><td class=\"examine\"><span id=\"examine\"  style=\"width: 50px;display: inline-block;text-align: left;\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"tt\"  >\r\n");
      out.write("\t\t  <div id=\"record_type_0\" title=\"意向客户\" data-options=\"selected:false,tabWidth:100\">   \r\n");
      out.write("\t         <div id='customerRecordType0GridDiv' style='width: 100%'> \r\n");
      out.write("\t         <table id='customerRecordType0Grid'></table>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t     \t<div id=\"customerRecordType0GridPager\" ></div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t     <div id=\"record_type_1\" title=\"未到诊\" data-options=\"selected:true,tabWidth:100\">\r\n");
      out.write("\t     \t<div id='customerRecordType1GridDiv' style='width: 100%'> \r\n");
      out.write("\t         <table id='customerRecordType1Grid'></table>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t     \t<div id=\"customerRecordType1GridPager\" ></div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <div id=\"record_type_2\" title=\"已到诊\" data-options=\"selected:false,tabWidth:100\">  \r\n");
      out.write("\t          <div id='customerRecordType2GridDiv' style='width: 100%'> \r\n");
      out.write("\t         <table id='customerRecordType2Grid'></table>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t     \t<div id=\"customerRecordType2GridPager\" ></div>\r\n");
      out.write("\t      </div>   \r\n");
      out.write("\t </div> \r\n");
      out.write("\t</div></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
