/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-11-03 06:42:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.ejanton.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CustomerView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/ejanton/customer/../../includeScript.jsp", Long.valueOf(1446121151261L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String context = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>首页</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/controls/controls.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/easyui-lang-zh_CN.js\"></script> \n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/controls/controls.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src='js/CustomerView.js'></script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t    \r\n");
      out.write("\t   <form id=\"customerForm\" class='view-form' method=\"post\">\r\n");
      out.write("            <table cellspacing='10'>\r\n");
      out.write("            \t<!-- <tr>\r\n");
      out.write("\t\t\t  \t\t <td align='left' class='td-label' colspan=\"4\" style=\"border-bottom: 1px solid #eee;\">基础信息</td>\r\n");
      out.write("\t\t\t  </tr> -->\r\n");
      out.write("\t\t\t  \t<tr>\r\n");
      out.write("                    <td align='right' class='td-label'>姓名：</td>\r\n");
      out.write("                    <td><label id='name' data-ssbtype='text' name=\"name\" ></label></td>\r\n");
      out.write("                     <td align='right' class='td-label'>性别：</td>\r\n");
      out.write("                    <td><label id='sex' data-ssbtype='int'  name=\"sex\"></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("                    <td align='right' class='td-label'>民族：</td>\r\n");
      out.write("                    <td><label id='nation' data-ssbtype='int'  name=\"nation\"></label></td>\r\n");
      out.write("                    <td align='right' class='td-label' >生日：</td>\r\n");
      out.write("                    <td><label id='birthDay' data-ssbtype='date' name=\"birthDay\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                \r\n");
      out.write("                \t<tr>\r\n");
      out.write("                    <td align='right' class='td-label'>身份证：</td>\r\n");
      out.write("                    <td><label id='cardId' data-ssbtype='text' name=\"cardId\" ></label></td>\r\n");
      out.write("                     <td align='right' class='td-label'>职业：</td>\r\n");
      out.write("                    <td><label id='occupation' data-ssbtype='int'  name=\"occupation\"></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t  <!-- <tr>\r\n");
      out.write("\t\t\t  \t\t <td align='left' class='td-label' colspan=\"4\" style=\"border-bottom: 1px solid #eee;\">联系方式</td>\r\n");
      out.write("\t\t\t  </tr> -->\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("                    <td align='right' class='td-label'>电话：</td>\r\n");
      out.write("                    <td><label id='phone' data-ssbtype='text' name=\"phone\" ></label></td>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    <td align='right' class='td-label'>QQ：</td>\r\n");
      out.write("                    <td><label id='qq' data-ssbtype='text' name=\"qq\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td align='right' class='td-label'>微信：</td>\r\n");
      out.write("                    <td><label id='weiXin' data-ssbtype='text' name=\"weiXin\" ></label></td>\r\n");
      out.write("                     <td align='right' class='td-label'>住址：</td>\r\n");
      out.write("                    <td><label id='address' data-ssbtype='text' name=\"address\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                 \t<tr>\r\n");
      out.write("                    <td align='right' class='td-label'>紧急联系电话：</td>\r\n");
      out.write("                    <td><label id='nstancyPhone' data-ssbtype='text' name=\"nstancyPhone\" ></label></td>\r\n");
      out.write("                       <td align='right' class='td-label'>紧急联系人姓名：</td>\r\n");
      out.write("                    <td><label id='nstancyName' data-ssbtype='text' name=\"nstancyName\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  <!--  \t<tr>\r\n");
      out.write("                   \r\n");
      out.write("                     <td align='right' class='td-label'>婚否</td>\r\n");
      out.write("                    <td><label id='married' data-ssbtype='int'  name=\"married\"></label></td>\r\n");
      out.write("                </tr> -->\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t<!--   <tr>\r\n");
      out.write("\t\t\t  \t\t <td align='left' class='td-label' colspan=\"4\" style=\"border-bottom: 1px solid #eee;\">患者情况</td>\r\n");
      out.write("\t\t\t  </tr> -->\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("                    <td align='right' class='td-label'>患者类型：</td>\r\n");
      out.write("                    <td><label id='patientType' data-ssbtype='int'  name=\"patientType\"></label></td>\r\n");
      out.write("                     <td align='right' class='td-label'>医保号：</td>\r\n");
      out.write("                    <td><label id='healthInsurance' data-ssbtype='text' name=\"healthInsurance\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t  \t<tr>\r\n");
      out.write("                    <td align='right' class='td-label'>家族病史：</td>\r\n");
      out.write("                    <td><label id='familyhistory' data-ssbtype='text' name=\"familyhistory\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t  \t<tr>\r\n");
      out.write("                    <td align='right' class='td-label'>过敏史：</td>\r\n");
      out.write("                    <td><label id='allergy' data-ssbtype='text' name=\"allergy\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t  <!--   <tr>\r\n");
      out.write("\t\t\t  \t\t <td align='left' class='td-label' colspan=\"4\" style=\"border-bottom: 1px solid #eee;\">记录患者日期</td>\r\n");
      out.write("\t\t\t  </tr> -->\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t  \t\t<td align='right' class='td-label'>营销人员：</td>\r\n");
      out.write("                    <td><label id='salesName' data-ssbtype='text' name=\"salesName\" ></label></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t       <tr>\r\n");
      out.write("\t\t\t        <td align='right' class='td-label'>创建人：</td>\r\n");
      out.write("                    <td><label id='createBy' data-ssbtype='text' name=\"createBy\" ></label></td>\r\n");
      out.write("                    <td align='right' class='td-label' >创建日期：</td>\r\n");
      out.write("                    <td><label id='createDate' data-ssbtype='date' name=\"createDate\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t       <tr>\r\n");
      out.write("\t\t\t          <td align='right' class='td-label'>修改人：</td>\r\n");
      out.write("                    <td><label id='lastUpdateBy' data-ssbtype='text' name=\"lastUpdateBy\" ></label></td>\r\n");
      out.write("                    <td align='right' class='td-label' >修改日期：</td>\r\n");
      out.write("                    <td><label id='lastUpdateDate' data-ssbtype='date' name=\"lastUpdateDate\" ></label></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t\t  <tr></tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("\t\r\n");
      out.write("\t     <div class='edit-form-btn dialog-btn'>\r\n");
      out.write("        \t<a class=\"easyui-linkbutton oper\"  data-options=\"iconCls:'icon-form-undo'\" onclick='cancel()'>关闭</a>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
