/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-11-16 09:39:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.ejanton.callback;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class CallbackEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/ejanton/callback/../../includeScript.jsp", Long.valueOf(1446121151261L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String context = request.getContextPath();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
Date now = new Date();
String now_day = sdf.format(now);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var now_day = '");
      out.print(now_day);
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t#lossFlag{\r\n");
      out.write("\t\t/* position: relative;\r\n");
      out.write("\t\ttop:3px;\r\n");
      out.write("\t\theight: 15px; width: 15px; */\r\n");
      out.write("\t}\r\n");
      out.write("\t#history{\r\n");
      out.write("\t\tfont-size:13px;\r\n");
      out.write("\t\tfont-family: \"Microsoft YaHei\" ! important;\r\n");
      out.write("\t\tpadding: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.clb_td{\r\n");
      out.write("\t\twidth:100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.clb_td_3cols{\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#west img:hover,\r\n");
      out.write("\t#newAppointment:hover,\r\n");
      out.write("\t.clb_td label:hover,\r\n");
      out.write("\t#lossFlag:hover,\r\n");
      out.write("\t.clb_td_3cols label:hover,\r\n");
      out.write("\t.label_for:hover{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#tab td{\r\n");
      out.write("\t}\r\n");
      out.write("\t.newAppointment{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.r_option{\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t\twidth: 62%;\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.curs_pointer:hover{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/controls/controls.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/easyui-lang-zh_CN.js\"></script> \n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/controls/controls.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(context);
      out.write("/app/ejanton/history/styles/History.css\">\r\n");
      out.write("\t<script src='js/CallbackEdit.js'></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"cc\" class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"west\" data-options=\"region:'west',split:true,border:false\"\r\n");
      out.write("\t\t\tstyle=\"border-color: blue; width: 510px\">\r\n");
      out.write("\t\t\t<form id=\"callbackForm\" class='edit-form' method=\"post\">\r\n");
      out.write("\t\t\t<input id=\"customerId\" name=\"customerId\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t<table cellspacing='10' id=\"tab\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100 height=40>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;客户姓名:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79% id=\"doNotCustomerName\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"normal-input\" id=\"customerName\" name=\"customerName\" style=\"width: 130px;\">  \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t<font color=red>*</font>回访类型:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width: 140px;\" class=\"easyui-combobox\" id='visitType' name=\"visitType\" data-ssbtype='combobox' \r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"height:30,valueField:'dictValue',textField:'dictName',panelHeight:'auto',editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"r_option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=red >*</font>时间:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"easyui-datetimebox\" id='visitTime' data-ssbtype='date' name=\"visitTime\"  \r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"height:30,editable:false,showSeconds:false\"style=\"width: 140px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"visitTime\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t<font color=red>*</font>回访方式:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-combobox\" id='visitWay' name=\"visitWay\" data-ssbtype='combobox'\r\n");
      out.write("\t\t\t\t\t\t\t data-options=\"height:30,valueField:'dictValue',textField:'dictName',panelHeight:120,editable:false\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 140px;\"> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;回访摘要:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"normal-input\" id=\"remarks\" name=\"remarks\" style=\"width: 100%;\">  \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"display: inline-block; height: 100px;\">&nbsp;回访内容:</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-textbox\" id=\"visitContent\" data-ssbtype=\"text\" name=\"visitContent\" data-options=\"multiline:true\" style=\"height: 100px;width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"display: inline-block; height: 100px;\">&nbsp;客户反应:</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-textbox\" id=\"customerReaction\" data-ssbtype=\"text\" name=\"customerReaction\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"multiline:true\" style=\"width: 100%; height: 100px\"> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"display: inline-block; height: 30px;\">&nbsp;客户评级:</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"20px\" height=\"20px\" class=\"star\" alt=\"星\" src=\"");
      out.print(context);
      out.write("/css/images/star_0.ico\" data-number=\"1\" data-select=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"20px\" height=\"20px\" class=\"star\" alt=\"星\" src=\"");
      out.print(context);
      out.write("/css/images/star_0.ico\" data-number=\"2\" data-select=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"20px\" height=\"20px\" class=\"star\" alt=\"星\" src=\"");
      out.print(context);
      out.write("/css/images/star_0.ico\" data-number=\"3\" data-select=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"20px\" height=\"20px\" class=\"star\" alt=\"星\" src=\"");
      out.print(context);
      out.write("/css/images/star_0.ico\" data-number=\"4\" data-select=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<img width=\"20px\" height=\"20px\" class=\"star\" alt=\"星\" src=\"");
      out.print(context);
      out.write("/css/images/star_0.ico\" data-number=\"5\" data-select=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t<label>&nbsp;注：到诊可能性，5星代表可能性100%</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- \t<div class=\"los_s\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"curs_pointer\" id='lossFlag' type=\"radio\" data-ssbtype='int'> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"curs_pointer\" for=\"lossFlag\" style=\"height: 30px; line-height: 1px;\">标记为流失</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;下次回访:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-datetimebox\"\r\n");
      out.write("\t\t\t\t\t\t\tid='nextVisitTime' data-ssbtype='date' name=\"nextVisitTime\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 130px;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"height:30,editable:false,showSeconds:false\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- <tr class=\"los_s\">\r\n");
      out.write("\t\t\t\t\t\t<td width=100 align=\"right\" height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;<input class=\"curs_pointer\" id='lossFlag' type=\"checkbox\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"label_for\" for=\"lossFlag\" style=\"width: 140px;display: inline-block;\">标记为流失</label>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"r_option los_s\"  id=\"lossSpan\"style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=red>*</font>流失类型:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-combobox\" id=\"lostType\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   data-options=\"height:30,width:140,panelHeight:'auto',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   valueField:'dictValue',textField:'dictName',editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100 align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;<input class=\"curs_pointer\" id='lossFlag' type=\"checkbox\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"label_for\" for=\"lossFlag\" style=\"width: 140px;display: inline-block;\">标记为流失</label>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;<input type=\"checkbox\" id=\"newAppointment\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"label_for\" for=\"newAppointment\">新增预约</label>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=100 align=\"right\" height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;<input type=\"checkbox\" id=\"newAppointment\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"label_for\" for=\"newAppointment\">新增预约</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t\t<tr class=\"los_s\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t<font color=red>*</font>流失类型:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-combobox\" id=\"lostType\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   data-options=\"height:30,width:140,panelHeight:'auto',\r\n");
      out.write("\t\t\t\t\t\t\t\t   valueField:'dictValue',textField:'dictName',editable:false\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"newAppointment\">\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t<font color=red>*</font>预约科室:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-combobox\" type=\"text\" id='appointmentOrg' data-ssbtype='combobox'  data-options=\"height:30,width:140,valueField:'orgId',textField:'name',onSelect:function(res){initDoc(res)},editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"r_option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=red>*</font>预约医生:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\" easyui-combobox\" type=\"text\" id='appointmentDoc' data-ssbtype='combobox'  data-options=\"height:30,width:140,valueField:'employeeId',textField:'name',onSelect:function(res){getDocName(res)},editable:false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id = \"appointmentDocName\">\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"newAppointment\">\r\n");
      out.write("\t\t\t\t\t\t<td width=100>\r\n");
      out.write("\t\t\t\t\t\t\t<font color=red>*</font>到诊时间:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=79%>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"easyui-datetimebox\" type=\"text\" id='checkTime' \r\n");
      out.write("\t\t\t\t\t\t\tdata-ssbtype='date' data-options=\"height:30,width:140,editable:false,showSeconds:false\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"r_option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;专家号:\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"display: inline-block; width: 130px; text-align: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"normal-input\" id=\"expertNumber\" disabled=\"disabled\" style=\"width:140px; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"center\" data-options=\"region:'center',split:true,border:false\" style=\"overflow: auto;\">\r\n");
      out.write("\t\t\t<div style='margin-top: 6px;' id='electronicHistoryGrid'></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class='edit_south' data-options=\"region:'south',split:true,border:false\">\r\n");
      out.write("\t\t\t<div class='edit-form-btn' style='float: right;margin-right:5px;'>\r\n");
      out.write("\t\t<a id='cancelBtn' class=\"easyui-linkbutton oper\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-form-undo'\" onclick='cancel()'>取消</a><!--  <a\r\n");
      out.write("\t\t\tid='deleteBtn' class=\"easyui-linkbutton oper\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-form-dustbin'\"\r\n");
      out.write("\t\t\tonclick='deleteCallback()'>删除</a>  --><a id='addBtn'\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton oper\"\r\n");
      out.write("\t\t\tstyle='margin-left: 10px; margin-right: 10px;'\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-form-ok'\" onclick='saveCallback()'>保存</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
