/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2016-01-25 02:16:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.exiaobao.campaign;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CampaignShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String context = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>商品详细</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print(context);
      out.write("/css/swiper/swiper.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link type=\"text/css\" href=\"css/style.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link type=\"text/css\" href=\"css/goodsView.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\tvar context= \"");
      out.print(context);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/swiper/swiper.min.js\"></script>\r\n");
      out.write("<script src='js/CampaignShow.js'></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"padding: 0;margin: 0;overflow:-Scroll;overflow-x:hidden;\">\r\n");
      out.write("<img id=\"swimg\" src=\"");
      out.print(context);
      out.write("/app/exiaobao/org/images/nopictrue_list.jpg\" border=\"0\" style=\"width:100%; \" />\r\n");
      out.write("\r\n");
      out.write("   <div id='goodsFormPanel'  title=\"\" style=\"width:100%;font-size:13px;margin:0;padding-left: 0\">\r\n");
      out.write("   <form id=\"goodsForm\"   method=\"post\" >\r\n");
      out.write("            <div class=\"swiper-container\" id=\"swiper-containerDIV\"  style=\"display: none\">\r\n");
      out.write("\t\t        <div class=\"swiper-wrapper\">\r\n");
      out.write("\t\t            <div class=\"swiper-slide\"><img src=\"images/img_main_3.jpg\" /></div>\r\n");
      out.write("\t\t            <div class=\"swiper-slide\"><img src=\"images/img_main_4.jpg\" /></div>\r\n");
      out.write("\t\t            <div class=\"swiper-slide\"><img src=\"images/img_main_5.jpg\" /></div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <!-- Add Pagination -->\r\n");
      out.write("\t\t        <div class=\"swiper-pagination\"></div>\r\n");
      out.write("\t\t        <div class=\"fdiv\"></div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("            <div class=\"ddiv\" >\r\n");
      out.write("            \t <table border=\"0\" >\r\n");
      out.write("            \t \t<tr>\r\n");
      out.write("            \t \t\t<td >\r\n");
      out.write("            \t \t\t\t<span id=\"goodsname\" style=\"font-size: 18px;color: #5A5A5A;font-weight:bold;\">\r\n");
      out.write("            \t \t\t\t</span>\r\n");
      out.write("            \t \t\t</td>\r\n");
      out.write("            \t \t</tr>\r\n");
      out.write("            \t \t<tr>\r\n");
      out.write("            \t \t\t<td style=\"padding-top: 0px;color: #BDBDBD\">\r\n");
      out.write("            \t \t\t\t销量:<span id=\"sales\" style=\"font-size: 14px;padding-left: 7px;margin-right: 50px;\"></span>\r\n");
      out.write("            \t \t\t\t推广量:<span id=\"chicknum\"  style=\"font-size: 14px;padding-left: 7px;\"></span>\r\n");
      out.write("            \t \t\t</td>\r\n");
      out.write("            \t \t</tr>\r\n");
      out.write("            \t \t<tr>\r\n");
      out.write("            \t \t\t<td style=\"padding-top: 4px;color: #BDBDBD;padding-bottom: 6px;\">\r\n");
      out.write("            \t \t\t\t<span id=\"discount\" style=\"color: #F8474A;font-size: 17px;\"></span>\r\n");
      out.write("            \t \t\t\t<span id=\"price\" style=\"text-decoration:line-through;color: #BDBDBD;margin-left: 6px\"></span>\r\n");
      out.write("            \t \t\t\t<span id=\"zhekou\"  style=\"color: #FF8C4B;margin-left: 10px;margin-right: 40px;\">7折</span>\r\n");
      out.write("            \t \t\t\t<span id=\"showbrokerage\">佣 金:</span><span id=\"brokerage\" style=\"color: #5A5A5A;padding-left: 7px;\"></span>\r\n");
      out.write("            \t \t\t</td>\r\n");
      out.write("            \t \t</tr>\r\n");
      out.write("            \t </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"backDiv\"></div>\r\n");
      out.write("            <div  id=\"tabbox\" style=\"height: auto;width: 100%;border-top: 0px solid #ddd;margin-top: 0px;\">\r\n");
      out.write("\t            <ul class=\"tabs\" id=\"tabs\" style=\"width: 100%;text-align: center;\">\r\n");
      out.write("\t               <li class=\"tabsli\" style=\"width: 10%\"></li>\r\n");
      out.write("\t\t\t       <li class=\"tabsli\" id=\"lia1\" style=\"width: 80%\"><a  href=\"#\" tab=\"tab1\"  >活动详细</a></li>\r\n");
      out.write("\t\t\t       <li class=\"tabsli\" style=\"width: 10%\"></li>\r\n");
      out.write("\t\t\t     </ul>\r\n");
      out.write("\t\t\t     <div class=\"backDiv\"></div>\r\n");
      out.write("\t\t\t    <ul class=\"tab_conbox\">\r\n");
      out.write("\t\t\t        <li id=\"tab1\" class=\"tab_con\">\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("       </form>\r\n");
      out.write("       <div class=\"butndiv\">\r\n");
      out.write("\t    \t<div id=\"bespeakBtn\" onclick=\"bespeak()\" style=\"width:130px;height:30px;background-image: url(’images/lijiyuyue.png')\">\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
