/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2016-01-30 08:18:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.exiaobao.org;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class OrgView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String context = request.getContextPath();
	String btnflag = request.getParameter("btnflag")==null?"":request.getParameter("btnflag");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>医院信息</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<link type=\"text/css\" href=\"css/Org.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link type=\"text/css\" href=\"");
      out.print(context);
      out.write("/css/swiper/swiper.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\tvar context= \"");
      out.print(context);
      out.write("\";\r\n");
      out.write("\tvar btnflag=\"");
      out.print(btnflag);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/swiper/swiper.min.js\"></script>\r\n");
      out.write("<script src='js/OrgView.js'></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"padding: 0;margin: 0;overflow:-Scroll;overflow-x:hidden;\">\r\n");
      out.write("<img id=\"swimg\" src=\"");
      out.print(context);
      out.write("/app/exiaobao/org/images/nopictrue_list.jpg\" border=\"0\" style=\"width:100%; \" />\r\n");
      out.write("\r\n");
      out.write("   <div id='orgFormPanel'  title=\"\" style=\"width:100%;font-size:13px;margin:0;padding-left: 0\">\r\n");
      out.write("   <form id=\"orgForm\"   method=\"post\" >\r\n");
      out.write("            <div class=\"swiper-container\" id=\"swiper-containerDIV\"  style=\"display: none\">\r\n");
      out.write("\t\t        <div class=\"swiper-wrapper\">\r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <!-- Add Pagination -->\r\n");
      out.write("\t\t        <div class=\"swiper-pagination\"></div>\r\n");
      out.write("\t\t        <div class=\"fdiv\"></div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("            <div class=\"ddiv\" >\r\n");
      out.write("            \t <table border=\"0\"  style=\"width: 100%\">\r\n");
      out.write("            \t \t<tr>\r\n");
      out.write("            \t \t\t<td colspan=\"3\" style=\"padding-top: 3px;\">\r\n");
      out.write("            \t \t\t\t<table border=\"0\"  style=\"width: 100%\">\r\n");
      out.write("\t\t        \t\t\t\t<tr>\r\n");
      out.write("\t\t        \t\t\t\t\t<td style=\"width: 30%\">\r\n");
      out.write("\t\t        \t\t\t\t\t\t<img  class=\"orgSmallimg\" src=\"");
      out.print(context);
      out.write("/app/exiaobao/org/images/nopictrue_user.gif\"  />\r\n");
      out.write("\t\t        \t\t\t\t\t</td>\r\n");
      out.write("\t\t        \t\t\t\t\t<td style=\"padding-left: 15px;padding-right: 10px;\">\r\n");
      out.write("\t\t        \t\t\t\t\t\t<ul >\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t<li id=\"orgname\" style=\"padding-bottom: 5px;font-size: 15px;\">\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t<li style=\"color: #BDBDBD;\" id=\"address\">\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t<li style=\"color: #BDBDBD;\" id=\"orgphone\">\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t        \t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t        \t\t\t\t\t</td>\r\n");
      out.write("\t\t        \t\t\t\t</tr>\r\n");
      out.write("\t\t        \t\t\t</table> \r\n");
      out.write("            \t \t\t</td>\r\n");
      out.write("            \t \t</tr>\r\n");
      out.write("            \t \t<tr style=\"text-align: center;\">\r\n");
      out.write("            \t \t\t<td style=\"padding-top: 5px;padding-bottom: 10px;\">\r\n");
      out.write("            \t \t\t\t<span style=\"color: #bbbbbb;\">商品：</span><span id=\"goodsNum\"></span>\r\n");
      out.write("            \t \t\t</td>\r\n");
      out.write("            \t \t\t<td style=\"padding-top: 5px;padding-bottom: 10px;\">\r\n");
      out.write("            \t \t\t\t<span style=\"color: #bbbbbb;\">销量：</span><span id=\"xsNum\"></span> \r\n");
      out.write("            \t \t\t</td>\r\n");
      out.write("            \t \t\t<td style=\"padding-top: 5px;padding-bottom: 10px;\">\r\n");
      out.write("            \t \t\t\t<span style=\"color: #bbbbbb;\">推广：</span><span id=\"tgNum\"></span> \r\n");
      out.write("            \t \t\t</td>\r\n");
      out.write("            \t \t</tr>\r\n");
      out.write("            \t </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"backDiv\" style=\"border-bottom: 0\"></div>\r\n");
      out.write("            <div class=\"searchDiv\">\r\n");
      out.write("            \t<div style=\"border: 0;padding: 0;margin: 0\">\r\n");
      out.write("            \t\t<input type=\"text\" class=\"keyword\" value=\"搜索医院商品\">\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<div class=\"searchBtn\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"backDiv\" style=\"border-top: 0;height: 5px;\"></div>\r\n");
      out.write("            \r\n");
      out.write("            <div  id=\"tabbox\" style=\"height: auto;width: 100%;border-top: 0px solid #ddd;margin-top: 0px;\">\r\n");
      out.write("\t            <ul class=\"tabs\" id=\"tabs\" style=\"width: 100%;text-align: center;\">\r\n");
      out.write("\t               <li class=\"tabsli\" style=\"width: 2%\"></li>\r\n");
      out.write("\t\t\t       <li class=\"tabsli\" id=\"lia1\" style=\"width: 32%\"><a  href=\"#\" tab=\"tab1\"  onclick=\"showClick('lia1','tab1')\">商品列表</a></li>\r\n");
      out.write("\t\t\t       <li class=\"tabsli\" id=\"lia2\" style=\"width: 32%\"><a  href=\"#\" tab=\"tab2\"  onclick=\"showClick('lia2','tab2')\">活动资讯</a></li>\r\n");
      out.write("\t\t\t       <li class=\"tabsli\" id=\"lia3\" style=\"width: 32%\"><a  href=\"#\" tab=\"tab2\"  onclick=\"showClick('lia3','tab3')\">医院简介</a></li>\r\n");
      out.write("\t\t\t       <li class=\"tabsli\" style=\"width: 2%\"></li>\r\n");
      out.write("\t\t\t     </ul>\r\n");
      out.write("\t\t\t     <div class=\"backDiv\" ></div>\r\n");
      out.write("\t\t\t    <ul class=\"tab_conbox\">\r\n");
      out.write("\t\t\t        <li id=\"tab1\" class=\"tab_con\" style=\"padding: 0;margin: 0\">\r\n");
      out.write("\t\t\t        \t<div>\r\n");
      out.write("\t\t\t        \t\t<table class=\"sortTb\">\r\n");
      out.write("\t\t\t        \t\t\t<tr style=\"\">\r\n");
      out.write("\t\t\t            \t \t\t<td  onclick=\"sjSort()\" style=\"width: 33%\">\r\n");
      out.write("\t\t\t            \t \t\t\t售价<span id=\"shoujaUp\" style=\"display: none;\">▲</span><span id=\"shoujaDown\" style=\"display: none;\">▼</span>\r\n");
      out.write("\t\t\t            \t \t\t</td>\r\n");
      out.write("\t\t\t            \t \t\t<td onclick=\"xlSort()\" style=\"width: 33%\">\r\n");
      out.write("\t\t\t            \t \t\t\t销量<span id=\"xialiangUp\" style=\"display: none;\">▲</span><span id=\"xialiangDown\" style=\"display: none;\">▼</span> \r\n");
      out.write("\t\t\t            \t \t\t</td>\r\n");
      out.write("\t\t\t            \t \t\t<td onclick=\"fwSort()\"> \r\n");
      out.write("\t\t\t            \t \t\t\t访问<span id=\"fangwenUp\" style=\"display: none;\">▲</span><span id=\"fangwenDown\" style=\"display: none;\">▼</span>\r\n");
      out.write("\t\t\t            \t \t\t</td>\r\n");
      out.write("\t\t\t            \t \t</tr>\r\n");
      out.write("\t\t\t        \t\t</table>\r\n");
      out.write("\t\t\t        \t</div>\r\n");
      out.write("\t\t\t        \t<ul id=\"showList\" style=\"border: 0;line-height: 90px;\">\r\n");
      out.write("\t\t\t        \t\t \r\n");
      out.write("\t\t\t        \t</ul>\r\n");
      out.write("\t\t\t        \t<div class=\"jiazaiged\" onclick=\"loadMore()\">\r\n");
      out.write("\t\t\t        \t\t加载更多\r\n");
      out.write("\t\t\t        \t</div>\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t        <li id=\"tab2\" class=\"tab_con\"  style=\"padding-left:2px;padding-right:2px;margin: 0\">\r\n");
      out.write("\t\t\t        \t \r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t         <li id=\"tab3\" class=\"tab_con\" style=\"padding: 0;margin: 0\">\r\n");
      out.write("\t\t\t         \t<div style=\"padding: 10px;padding-top: 5px;\">\r\n");
      out.write("\t\t\t         \t\t<span style=\"color:#BDBDBD \">医院简介：</span>\r\n");
      out.write("\t\t\t         \t\t<p id=\"introduction\" style=\"padding: 0;margin: 0;text-indent:25px\"></p>\r\n");
      out.write("\t\t\t         \t</div>\r\n");
      out.write("\t\t\t         \t<div class=\"backDiv\"></div>\r\n");
      out.write("\t\t\t         \t<div style=\"padding-top: 5px;padding-bottom: 5px;padding-left: 10px;\">\r\n");
      out.write("\t\t\t         \t\t<span style=\"color:#BDBDBD \">地址：</span><span id=\"tabaddress\"></span>\r\n");
      out.write("\t\t\t         \t</div>\r\n");
      out.write("\t\t\t         \t<div class=\"backDiv\"></div>\r\n");
      out.write("\t\t\t         \t<div style=\"padding-bottom: 40px;color:#BDBDBD;padding-left: 10px; \" >\r\n");
      out.write("\t\t\t         \t\t<span style='color:#BDBDBD'>联系电话：</span><span id=\"tabphone\"></span>\r\n");
      out.write("\t\t\t         \t</div>\r\n");
      out.write("\t\t\t        </li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("       </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
