/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-12-29 03:05:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.exiaobao.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Goodsinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String context = request.getContextPath();
	String operationSet = request.getAttribute("operations")==null?"-1":request.getAttribute("operations").toString();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>首页</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\tvar context= \"");
      out.print(context);
      out.write("\";\r\n");
      out.write("\tvar operationSet=\"");
      out.print(operationSet);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(context);
      out.write("/js/jqueryMoblie/jquery.mobile-1.4.5.css\">\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/jqueryMoblie/jquery.mobile-1.4.5.min.js\"></script>\r\n");
      out.write("<script src='js/Goodsinfo.js'></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div data-role=\"page\" data-theme=\"a\">\r\n");
      out.write("\t\t<div data-role=\"content\">\r\n");
      out.write("\t\t\t<div id=\"demo1\"> \r\n");
      out.write("\t\t\t\t<img src=\"http://pic2.ooopic.com/01/03/51/25b1OOOPIC19.jpg\" alt=\"图片\"> \r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<div class=\"ui-grid-a\">\r\n");
      out.write("\t\t\t\t<div class=\"ui-block-a\" style=\"border: 1px solid black;border-right: 0px;\">\r\n");
      out.write("\t\t\t       <span>关爱价：￥100</span>\r\n");
      out.write("\t\t\t     </div>\r\n");
      out.write("\t\t\t     <div class=\"ui-block-b\" style=\"border: 1px solid black;\">\r\n");
      out.write("\t\t\t       <span>佣金比例：20%</span>\r\n");
      out.write("\t\t\t     </div>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"ui-grid-a\" > \r\n");
      out.write("\t\t\t\t<div class=\"ui-block-a\" style=\"border: 1px solid black;border-top: 0px;border-right: 0px; \">\r\n");
      out.write("\t\t\t       <span>原价：￥100</span>\r\n");
      out.write("\t\t\t     </div>\r\n");
      out.write("\t\t\t     <div class=\"ui-block-b\" style=\"border: 1px solid black;border-top: 0px; \">\r\n");
      out.write("\t\t\t       <span>佣金：￥20</span>\r\n");
      out.write("\t\t\t     </div>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"ui-grid-b\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t     <div class=\"ui-block-a\"  ><span>地点: 深圳市</span></div>\r\n");
      out.write("\t\t     <div class=\"ui-block-b\"  style=\"text-align: center;\"><span>销量: Text</span></div>\r\n");
      out.write("\t\t     <div class=\"ui-block-c\"  style=\"text-align: right;\"><span>有78购买</span></div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t\t<div data-role=\"collapsible-set\">\r\n");
      out.write("\t\t      <div data-role=\"collapsible\" data-collapsed=\"false\">\r\n");
      out.write("\t\t        <h3>项目详细</h3>\r\n");
      out.write("\t\t  \t    <p></p>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div data-role=\"collapsible\">\r\n");
      out.write("\t\t        <h3>规格明细</h3>\r\n");
      out.write("\t\t        <p>我是可折叠的内容。</p>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div data-role=\"collapsible\">\r\n");
      out.write("\t\t        <h3>分享说明</h3>\r\n");
      out.write("\t\t        <p>我是可折叠的内容。</p>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write(" \t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
