/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-12-07 05:26:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.lang3.StringUtils;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>医小宝系统</title>\r\n");
      out.write("\r\n");

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"css/images/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/login.css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar operationSet=\"\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if(top.indexAttr&&top.indexAttr.top){\r\n");
      out.write("\tvar browser = navigator.userAgent;\r\n");
      out.write("\tif(browser.indexOf(\"Chrome\")!= -1 || browser.indexOf(\"Firefox\") != -1){\r\n");
      out.write("\t\ttop.window.location =\"");
      out.print(context);
      out.write("/login.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\ttop.window.location = \"");
      out.print(context);
      out.write("/login.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar user = tcCore.getCookie(\"user\");\r\n");
      out.write("\t\tvar password = tcCore.getCookie(\"password\");\r\n");
      out.write("\t\tif(user){\r\n");
      out.write("\t\t\t$(\"#username\").val(user);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(password){\r\n");
      out.write("\t\t\t$(\"#password\").val(password);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar a = tcCore.getParameter(\"validatefaild\");\r\n");
      out.write("\t\tif (a == 1) {\r\n");
      out.write("\t\t\talert(\"用户名或者密码错误\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#loginCheck\").click(function() {\r\n");
      out.write("\t\t\tif (!$(this).hasClass(\"login_check_checked\")) {\r\n");
      out.write("\t\t\t\t$(this).addClass(\"login_check_checked\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"login_check_checked\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#loginCheck\")\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class='login_header'>\r\n");
      out.write("\t\t<div class='center_div'>\r\n");
      out.write("\t\t\t<img class='welcome_login' src='css/images/welcome_login.png'>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class='login_body'>\r\n");
      out.write("\t\t<div class='center_div'>\r\n");
      out.write("\t\t\t<img class='earth' src='css/images/earth_merge.png'>\r\n");
      out.write("\t\t\t<form autocomplete=\"off\" class='login_form' method=\"post\"\r\n");
      out.write("\t\t\t\taction=\"");
      out.print(context);
      out.write("/login\">\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t<p style='margin-top: 95px;'>\r\n");
      out.write("\t\t\t\t\t<input\r\n");
      out.write("\t\t\t\t\t\tstyle='padding-left: 10px; width: 245px; height: 35px; background-color: #FFF; border-width: 0px;'\r\n");
      out.write("\t\t\t\t\t\tid=\"username\" name=\"username\" required=\"required\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"手机号\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<input\r\n");
      out.write("\t\t\t\t\t\tstyle='padding-left: 10px; margin-top: 5px; width: 245px; height: 35px; background-color: #FFF; border-width: 0px;'\r\n");
      out.write("\t\t\t\t\t\tid=\"password\" name=\"pwd\" required=\"required\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"密码\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style='margin-top: 5px; text-align: left;'>\r\n");
      out.write("\t\t\t\t\t<a id='loginCheck' class='login_check'>记住密码</a> \r\n");
      out.write("\t\t\t\t\t<!--  a\r\n");
      out.write("\t\t\t\t\t\tclass='login_forget_password'>忘记密码</a-->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style='margin-top: 5px; height: 45px;'>\r\n");
      out.write("\t\t\t\t\t<input class='login_btn' type=\"submit\" value=\"\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style='margin-top: 10px;'>\r\n");
      out.write("\t\t\t\t\t<!--  a class='login_register'></a-->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class='login_footer'>\r\n");
      out.write("\t\t<div class='center_div'>\r\n");
      out.write("\t\t\t<a class='footer_link'>关于我们</a> <a class='footer_link'>服务条款</a> <a\r\n");
      out.write("\t\t\t\tclass='footer_link'>客服中心</a> <a class='footer_link'>联系我们</a> <a\r\n");
      out.write("\t\t\t\tclass='footer_link'>帮助中心</a> <a class='footer_link'>深圳医建通网络科技有限公司</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
