/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2016-01-30 08:24:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.oms.org;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xt.ssb.util.Constants;
import java.util.HashMap;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import com.xt.privilege.empower.bussiness.EmpowerDS;
import com.xt.ssb.util.Constants;

public final class OrgVeiw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/oms/org/../../includeScript.jsp", Long.valueOf(1448597232733L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String context = request.getContextPath();
	String uphone=request.getSession().getAttribute(Constants.session_employee_phone)+"";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var uphone=\"");
      out.print(uphone);
      out.write("\";\r\n");
      out.write("var context=\"");
      out.print(context);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".div1{\r\n");
      out.write("\tfloat: left;border: 1px solid #ddd;width: 200px;height: 150px;margin-left: 20px;margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write(".div2{\r\n");
      out.write("\tfloat: left;width: 600px;padding: 0;padding-left: 20px;margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write(".divx{\r\n");
      out.write("\tposition:fixed;height: 30px;width: 200px;top:190px;background: #1F90C8;text-align: center;z-index:100;\r\n");
      out.write("\tpadding-top: 8px;color: white;font-weight: 600;cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
	//Long employeeIde = Long.parseLong(request.getSession().getAttribute(Constants.session_employee_id)+"");
	String operationSet = request.getAttribute("operations")==null?"-1":request.getAttribute("operations").toString();
	
	//String uri = //获取当前页的url
			//截取app 后面的 发到后台 获取操作资源的 identityName   print

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t\tvar operationSet = \"");
      out.print(operationSet);
      out.write("\";\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/controls/controls.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/easyui-lang-zh_CN.js\"></script> \n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/controls/controls.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(context );
      out.write("/js/swfupload/swfupload.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(context );
      out.write("/js/swfupload/handlers.js\"></script>\r\n");
      out.write("<script src='js/OrgVeiw.js'></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"cc\" class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t<div id='center' data-options=\"region:'center',border:false\" style=\"padding: 5px;\">\r\n");
      out.write("\t\t\t<div id='orgFormPanel' class='easyui-panel' title=\"医院信息\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%; font-size: 13px;\"\r\n");
      out.write("\t\t\t\tdata-options=\"iconCls:'icon-form-edit',region:'north'\">\r\n");
      out.write("\t\t\t\t<form id=\"orgForm\" class='edit-form' method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"div1\"  >\r\n");
      out.write("\t\t\t\t\t\t<div id=\"logo\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div  class=\"divx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"orgLogoBtn\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"div2\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing='0' style=\"width: 100%;border: 0;padding: 0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align='right' class='td-label' >医院名称:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label type=\"text\" id='name' name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200\"></label></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align='right' class='td-label'>电话号: </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label type=\"text\" id='phone' name=\"phone\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200\"></label></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align='right' class='td-label'>公&nbsp;众&nbsp;号:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label id='wxaccount' name=\"wxaccount\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200\"></label></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align='right' class='td-label'>地&nbsp;&nbsp;址:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label id='address' name=\"address\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"height:30,width:200\"></label></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align='right' class='td-label' valign=\"top\">医院简介:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id='introduction' name=\"introduction\" style=\"width:500px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div style=\"width: 800px;padding-top: 180px;padding-left: 20px;\">\r\n");
      out.write("\t\t\t\t\t<div id='orgimg' style=\"padding-top: 50px;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"width: 800px;padding-top: 40px;padding-left: 20px;padding-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t<div class='edit-form-btn' style='text-align:center;'>\r\n");
      out.write("\t\t\t\t\t\t<a id='deleteBtn' class=\"easyui-linkbutton oper\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"iconCls:'icon-form-ok'\" onclick='editOrg()'>编辑</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton oper\" style='margin-left:30px;'\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"iconCls:'icon-form-search-btn'\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick='queryOrg()'>查看</a>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction initSwfUpload() {\r\n");
      out.write("\t\t\tnew SWFUpload({\r\n");
      out.write("\t\t\t\tupload_url: context+\"/fileupload\",\r\n");
      out.write("\t\t\t\tpost_params: {\"name\" : \"test\"},\r\n");
      out.write("\t\t\t\t// File Upload Settings\r\n");
      out.write("\t\t\t\tfile_size_limit : \"2 MB\",\t// 1000MB\r\n");
      out.write("\t\t\t\tfile_types : \"*.gif;*.png;*.jpg;*.jpeg\",\r\n");
      out.write("\t\t\t\tfile_types_description : \" \",\r\n");
      out.write("\t\t\t\tfile_upload_limit : \"1\",\r\n");
      out.write("\t\t\t\tfile_queue_error_handler : fileQueueError,\r\n");
      out.write("\t\t\t\tfile_dialog_complete_handler : fileDialogComplete,//选择好文件后提交\r\n");
      out.write("\t\t\t\tfile_queued_handler : fileQueued,\r\n");
      out.write("\t\t\t\tupload_progress_handler : uploadProgress,\r\n");
      out.write("\t\t\t\tupload_error_handler : uploadError,\r\n");
      out.write("\t\t\t\tupload_success_handler : uploadSuccess,\r\n");
      out.write("\t\t\t\tupload_complete_handler : uploadComplete,\r\n");
      out.write("\t\t\t\t// Button Settings\r\n");
      out.write("\t\t\t\tbutton_placeholder_id : \"orgLogoBtn\",\r\n");
      out.write("\t\t\t\tbutton_width: 200,\r\n");
      out.write("\t\t\t\tbutton_height: 18,\r\n");
      out.write("\t\t\t\tbutton_text : '<span class=\"button\"  >上传Logo</span>',\r\n");
      out.write("\t\t\t\tbutton_text_style : '.button { font-size: 12pt;margin-left:55px; } .buttonSmall { font-size: 14pt; }',\r\n");
      out.write("\t\t\t\tbutton_text_top_padding: 0,\r\n");
      out.write("\t\t\t\tbutton_text_left_padding: 18,\r\n");
      out.write("\t\t\t\tbutton_window_mode: SWFUpload.WINDOW_MODE.TRANSPARENT,\r\n");
      out.write("\t\t\t\tbutton_cursor: SWFUpload.CURSOR.HAND,\r\n");
      out.write("\t\t\t\t// Flash Settings\r\n");
      out.write("\t\t\t\tflash_url : context+\"/js/swfupload/swfupload.swf\",\r\n");
      out.write("\t\t\t\tdebug: false  //是否显示调试窗口\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
