/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2016-01-12 06:51:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.wx.payacc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import com.xt.privilege.empower.bussiness.EmpowerDS;
import com.xt.ssb.util.Constants;

public final class payaccEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/wx/payacc/../../includeScript.jsp", Long.valueOf(1448597232733L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String context = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bootstrap 101 Template</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
	//Long employeeIde = Long.parseLong(request.getSession().getAttribute(Constants.session_employee_id)+"");
	String operationSet = request.getAttribute("operations")==null?"-1":request.getAttribute("operations").toString();
	
	//String uri = //获取当前页的url
			//截取app 后面的 发到后台 获取操作资源的 identityName   print

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t\tvar operationSet = \"");
      out.print(operationSet);
      out.write("\";\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/controls/controls.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/easyui-lang-zh_CN.js\"></script> \n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/controls/controls.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(context);
      out.write("/js/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("\r\n");
      out.write("<!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 自定义修改css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(context);
      out.write("/js/bootstrap/css/layoutit.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src='js/payaccEdit.js'></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin: 5px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t<h3 class=\"panel-title\">微信支付交易</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<h4>设置自有微信支付，买家使用微信支付付款购买商品时，货款将直接进入您微信支付对应的财付通账户。</h4>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" role=\"form\"  id=\"wxAppPayForm\"  method=\"post\">\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"accountName\" class=\"col-sm-2 control-label\">当前微信支付：\r\n");
      out.write("             </label> \r\n");
      out.write("\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label class=\"radio inline\"> 微信支付 - 自有 修改: </label> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"alert alert-warning alert-dismissable\">\r\n");
      out.write("                            <p>\r\n");
      out.write("\t\t\t\t\t\t\t注意：使用自有微信支付，货款直接入账至您的财付通账户，由财付通自动扣除每笔0.6%交易手续费。\r\n");
      out.write("\t\t\t\t\t\t\t\t订单如需退款，请自行通过财务通后台手动完成退款操作，并在订单中做“标记退款”。 <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_blank\" class=\"new-window\">查看设置教程</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t </div>             \r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("       \r\n");
      out.write("       <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"mchId\" class=\"col-sm-2 control-label\">商户号:</label> \r\n");
      out.write("\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"mchId\" name=\"mchId\" placeholder=\"商户号\" maxlength=\"10\">\r\n");
      out.write("\t\t\t<p class=\"help-block\">请填写微信发给您的邮件中的商户号，不是您财付通的商户号</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--         <div class=\"form-group\"> -->\r\n");
      out.write("<!-- \t\t\t<label for=\"partnerKey\" class=\"col-sm-2 control-label\">PaySignKey:</label>  -->\r\n");
      out.write("<!-- \t\t\t<div class=\"col-sm-5\"> -->\r\n");
      out.write("<!-- \t\t\t<p style=\"margin: 2px 0 6px;\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t2014年9月10日后申请微信支付免交保证金的商家，<br>若无PaySignKey，可免填。 -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t</p> -->\r\n");
      out.write("<!-- \t\t\t<textarea class=\"form-control\" id=\"partnerKey\" name=\"partnerKey\"  cols=\"60\" rows=\"5\" -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\tmaxlength=\"128\"></textarea> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("<!-- \t\t </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"paySignKey\" class=\"col-sm-2 control-label\"><em class=\"required\">*</em>密钥:</label> \r\n");
      out.write("\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"paySignKey\" name=\"paySignKey\"  placeholder=\"密钥\"  \r\n");
      out.write("\t\t\t\t\t\t\t\t  maxlength=\"32\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"payTest\" class=\"col-sm-2 control-label\" for=\"payTest\">微信支付状态:</label> \r\n");
      out.write("\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label class=\"checkbox-inline\">\r\n");
      out.write("      <input type=\"radio\" name=\"payTest\" id=\"payTest\" \r\n");
      out.write("         value=\"0\" checked> 全网支付已发布\r\n");
      out.write("   </label>\r\n");
      out.write("   <label class=\"checkbox-inline\">\r\n");
      out.write("      <input type=\"radio\" name=\"payTest\" id=\"payTest\" \r\n");
      out.write("         value=\"1\"> 测试支付中\r\n");
      out.write("   </label>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"alert alert-warning alert-dismissable  js-pay-all\">\r\n");
      out.write("                            <p>\r\n");
      out.write("\t\t\t\t\t\t\t\t由于微信支付流程限制，该选项需由您进行设置。如您的微信支付已通过微信的审核并开通，请选择“全网支付已发布”状态，以保证粉丝能够在你的店铺正常使用微信支付进行交易。否则，请选择“测试支付中”；\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"alert alert-warning alert-dismissable  js-pay-part  hide\">\r\n");
      out.write("                         \r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t由于微信支付流程限制，该选项需由您进行设置。如您的微信支付正处在微信审核测试中，请选择“测试支付中”的状态，以保证能通过微信审核。若已审核同通过并已开通全网支付，请选择“全网支付已发布”；\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\t\t\t </div>             \r\n");
      out.write("\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"domainAuth\" class=\"col-sm-2 control-label\">微信网页授权:</label> \r\n");
      out.write("\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t<label class=\"checkbox inline\"> <input name=\"domainAuth\" value=\"1\" type=\"checkbox\" checked=\"\">授权回调页面域名已设置为“xxx.xxx.com”\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"domainName\" class=\"col-sm-2 control-label\"><em class=\"required\">*</em>服务器域名:</label> \r\n");
      out.write("\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"domainName\" name=\"domainName\"  placeholder=\"服务器域名\">\r\n");
      out.write("\t\t\t\t<p class=\"help-block\">头部要包含http或https，，以左斜杠“/”结尾。</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"form-group\">\r\n");
      out.write("      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn_primary save_submit\">提 &nbsp;&nbsp;交</button>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- panel-body  end -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- panel  end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("   $(function() { \r\n");
      out.write("\t   init();\r\n");
      out.write("      $(\".save_submit\").click(function(){\r\n");
      out.write("    \t saveWXapp();\r\n");
      out.write("      });\r\n");
      out.write("   });  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
