/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-10-12 04:11:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.ejanton.history;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class HistorySearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/ejanton/history/../../includeScript.jsp", Long.valueOf(1444619467078L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  \r\n");

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>History查询</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/address.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src='js/HistorySearch.js'></script>\r\n");
      out.write("\t<form id=\"historyForm\" class='search-form' method=\"post\">\r\n");
      out.write("\t\t<table cellpadding=\"10\" style='width:100%;'>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table id=\"historyTable\" style='width:100%;' >\r\n");
      out.write("\t\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align='right' class='td-label'>患者编号</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input class=\" easyui-numberbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tid='customerId' data-ssbtype='int'\r\n");
      out.write("\t\t\t\t\t\tname=\"customerId\" data-options=\"height:30,width:200\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align='right' class='td-label'>病历号</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input class=\" easyui-numberbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tid='medicalnumber' data-ssbtype='int'\r\n");
      out.write("\t\t\t\t\t\tname=\"medicalnumber\" data-options=\"height:30,width:200\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>主诉</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"chief\"  name=\"chief\" data-options=\"height:30\"></input></td>\r\n");
      out.write("  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t<tr class='shouldhidden'>\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>现病史</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"hpc\"  name=\"hpc\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>病种</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"diseasetype\"  name=\"diseasetype\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>发病症状</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"diseasesymptom\"  name=\"diseasesymptom\" data-options=\"height:30\"></input></td>\r\n");
      out.write("  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t<tr class='shouldhidden'>\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>临床诊断</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"clinical\"  name=\"clinical\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>检查部位</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"position\"  name=\"position\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>检查项目</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"checkpr\"  name=\"checkpr\" data-options=\"height:30\"></input></td>\r\n");
      out.write("  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t<tr class='shouldhidden'>\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>医生</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"doctor\"  name=\"doctor\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>科室</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"section\"  name=\"section\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>治疗中照片</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"tinpho\"  name=\"tinpho\" data-options=\"height:30\"></input></td>\r\n");
      out.write("  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t<tr class='shouldhidden'>\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>治疗前照片</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"tbeforepho\"  name=\"tbeforepho\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>治疗前说明</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"beforethat\"  name=\"beforethat\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>治疗后照片</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"tlastpho\"  name=\"tlastpho\" data-options=\"height:30\"></input></td>\r\n");
      out.write("  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t<tr class='shouldhidden'>\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>治疗中说明</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"inthat\"  name=\"inthat\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>治疗后说明</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"lastthat\"  name=\"lastthat\" data-options=\"height:30\"></input></td>\r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align='right' class='td-label'>关联预约记录</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"record\"  name=\"record\" data-options=\"height:30\"></input></td>\r\n");
      out.write("  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t<tr class='shouldhidden'>\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td align='right' class='td-label'>记录日期</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"hidden\" id='date' value='1'\r\n");
      out.write("\t\t\t\t\t\t\tdata-ssbtype='dateRange' name=\"date\"></input> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-datebox\" type=\"text\" id='dateStart'\r\n");
      out.write("\t\t\t\t\t\t\tdata-ssbtype='date'\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,width:120,height:30\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t- <input class=\"easyui-datebox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid='dateEnd' data-ssbtype='date'\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,width:120,height:30\"></input>\r\n");
      out.write("\t\t\t\t\t\t</td>       \r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td align='right' class='td-label'>createDate</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"hidden\" id='createDate' value='1'\r\n");
      out.write("\t\t\t\t\t\t\tdata-ssbtype='dateRange' name=\"createDate\"></input> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-datebox\" type=\"text\" id='createDateStart'\r\n");
      out.write("\t\t\t\t\t\t\tdata-ssbtype='date'\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,width:120,height:30\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t- <input class=\"easyui-datebox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid='createDateEnd' data-ssbtype='date'\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,width:120,height:30\"></input>\r\n");
      out.write("\t\t\t\t\t\t</td>       \r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t<tr class='shouldhidden'>\r\n");
      out.write("\t\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td align='right' class='td-label'>lastUpdateDate</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"hidden\" id='lastUpdateDate' value='1'\r\n");
      out.write("\t\t\t\t\t\t\tdata-ssbtype='dateRange' name=\"lastUpdateDate\"></input> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-datebox\" type=\"text\" id='lastUpdateDateStart'\r\n");
      out.write("\t\t\t\t\t\t\tdata-ssbtype='date'\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,width:120,height:30\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t- <input class=\"easyui-datebox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid='lastUpdateDateEnd' data-ssbtype='date'\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"formatter:tcCoreformatter,parser:tcCoreParser,width:120,height:30\"></input>\r\n");
      out.write("\t\t\t\t\t\t</td>       \r\n");
      out.write("\t\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("   \r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td align='left' vAlign='bottom' style='width:180px;'>\r\n");
      out.write("\t\t\t\t\t<a class='moreBtn' id='moreConditionBtn'>更多↓</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton search\" style='margin-left:30px;'\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-form-search-btn'\"\r\n");
      out.write("\t\t\t\t\tonclick='queryHistory()'>查询</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id='operbtn' class='operbtn'\r\n");
      out.write("\t\tstyle='margin-top: 15px; margin-bottom: 15px;'>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"addData()\">新增</a> <a\r\n");
      out.write("\t\t\thref=\"#\" class=\"easyui-linkbutton\" onclick=\"editDataBtnClick()\">修改</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"deleteDataBtnClick()\">删除</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"print()\">打印</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='historyGridDiv' style='width: 100%'>\r\n");
      out.write("\t\t<table id='historyGrid'></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"historyGridPager\" />\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
