/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2016-01-28 12:00:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.exiaobao.bespeak;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BespeakEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("  \r\n");

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\tvar context= \"");
      out.print(context);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/BespeakEdit.css\">\r\n");
      out.write("<script src=\"");
      out.print(context);
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src='js/BespeakEdit.js'></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"text-align: center;\">\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<h2>预约</h2>\r\n");
      out.write("\t\t<div class=\"in2\">\r\n");
      out.write("\t\t\t<input type=\"hidden\"   id=\"goodsid\" name=\"goodsid\"  value=\"\">\r\n");
      out.write("\t\t\t <input type=\"hidden\"   id=\"campaignid\" name=\"campaignid\"  value=\"\">\r\n");
      out.write("\t\t\t <input type=\"hidden\"   id=\"phone\" name=\"phone\"  value=\"\">\r\n");
      out.write("\t\t\t <input type=\"hidden\"   id=\"price\" name=\"price\"  value=\"\">\r\n");
      out.write("\t\t\t <input type=\"text\"  name=\"usrname\" id=\"usrname\"   placeholder=\"您的姓名\"  >\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t <input type=\"text\" name=\"bespeakphone\" id=\"bespeakphone\" placeholder=\"手机号码\" min=\"11\" max=\"11\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button class=\"bbb1\" type=\"button\" id=\"yuyue\" onclick=\"subform()\">预约</button>\r\n");
      out.write("\t\t<button class=\"bbb2\" type=\"button\" id=\"zhifu\" onclick=\"subform2()\">预约并支付</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
