/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-11-18 02:32:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.fileupload.swfupload;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import com.xt.privilege.empower.bussiness.EmpowerDS;
import com.xt.ssb.util.Constants;

public final class upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/app/fileupload/swfupload/../../includeScript.jsp", Long.valueOf(1447697011984L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"swfupload.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"swfupload.queue.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"handlers.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("      var swfu;\r\n");
      out.write("      window.onload = function () {\r\n");
      out.write("        swfu = new SWFUpload({\r\n");
      out.write("          upload_url: \"");
      out.print(context );
      out.write("/fileupload\",\r\n");
      out.write("          post_params: {\"name\" : \"zwm\"},\r\n");
      out.write("          use_query_string:true,//这块必须设置，要不然在后台处理的时候是没法获得name的值的\r\n");
      out.write("          // File Upload Settings\r\n");
      out.write("          file_size_limit : \"10 MB\",\t// 文件大小控制\r\n");
      out.write("          file_types : \"*.jpg;*.gif\",\r\n");
      out.write("          file_types_description : \"Web Image Files\",\r\n");
      out.write("          file_upload_limit : \"0\",\r\n");
      out.write("                  \r\n");
      out.write("          file_queue_error_handler : fileQueueError,\r\n");
      out.write("          file_dialog_complete_handler : fileDialogComplete,//选择好文件后提交\r\n");
      out.write("          file_queued_handler : fileQueued,\r\n");
      out.write("          upload_progress_handler : uploadProgress,\r\n");
      out.write("          upload_error_handler : uploadError,\r\n");
      out.write("          upload_success_handler : uploadSuccess,\r\n");
      out.write("          upload_complete_handler : uploadComplete,\r\n");
      out.write("          button_placeholder_id : \"spanButtonPlaceholder\",\r\n");
      out.write("          button_width: 180,\r\n");
      out.write("          button_height: 18,\r\n");
      out.write("          button_text : '添加附件',\r\n");
      out.write("          button_text_style : '.button { font-family: Helvetica, Arial, sans-serif; font-size: 12pt; } .buttonSmall { font-size: 10pt; }',\r\n");
      out.write("          button_text_top_padding: 0,\r\n");
      out.write("          button_text_left_padding: 18,\r\n");
      out.write("          button_window_mode: SWFUpload.WINDOW_MODE.TRANSPARENT,\r\n");
      out.write("          button_cursor: SWFUpload.CURSOR.HAND,\r\n");
      out.write("          button_image_url:\"../bton.png\",\r\n");
      out.write("          // Flash Settings\r\n");
      out.write("          flash_url : \"swfupload.swf\",\r\n");
      out.write("  \r\n");
      out.write("          custom_settings : {\r\n");
      out.write("        \t  progressTarget : \"divFileProgressContainer\"\r\n");
      out.write("          },\r\n");
      out.write("          // Debug Settings\r\n");
      out.write("          debug: false  //是否显示调试窗口\r\n");
      out.write("        });\r\n");
      out.write("      };\r\n");
      out.write("      function startUploadFile(){\r\n");
      out.write("        swfu.startUpload();\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
	//Long employeeIde = Long.parseLong(request.getSession().getAttribute(Constants.session_employee_id)+"");
	String operationSet = request.getAttribute("operations")==null?"-1":request.getAttribute("operations").toString();
	
	//String uri = //获取当前页的url
			//截取app 后面的 发到后台 获取操作资源的 identityName   print

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<script type='text/javascript'>\n");
      out.write("\t\tvar context= \"");
      out.print(context);
      out.write("\";\n");
      out.write("\t\tvar operationSet = \"");
      out.print(operationSet);
      out.write("\";\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/metro/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/easyui/themes/icon.css\">\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/css/style.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"");
      out.print(context);
      out.write("/js/controls/controls.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/form.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/easyui/easyui-lang-zh_CN.js\"></script> \n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/controls/controls.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/scroll/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/core/core.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/browser.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/lib/jquery.ajaxQueue.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(context);
      out.write("/js/jquery-autocomplete/jquery.autocomplete.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.min.css' rel='stylesheet' />\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lib/moment.min.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/fullcalendar.js'></script>\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/fullcalendar/lang-all.js'></script>\n");
      out.write("\t\n");
      out.write("\t<link href='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.theme.min.css' rel='stylesheet' />\n");
      out.write("\t<script src='");
      out.print(context);
      out.write("/js/jquery-ui-auto/jquery-ui.min.js'></script>\n");
      out.write("\t\n");
      out.write("\t -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("      <form>\r\n");
      out.write("        <div style=\"display: inline; border: solid 1px #7FAAFF; background-color: #C5D9FF; padding: 2px;\">\r\n");
      out.write("          <span id=\"spanButtonPlaceholder\"></span>\r\n");
      out.write("          <input id=\"btnUpload\" type=\"button\" value=\"上  传\"\r\n");
      out.write("            onclick=\"startUploadFile();\" class=\"btn3_mouseout\"   />\r\n");
      out.write("          <input id=\"btnCancel\" type=\"button\" value=\"取消所有上传\"\r\n");
      out.write("            onclick=\"cancelUpload();\" disabled=\"disabled\" class=\"btn3_mouseout\"  />\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("      <div id=\"divFileProgressContainer\"></div>\r\n");
      out.write("      <div id=\"thumbnails\">\r\n");
      out.write("        <table id=\"infoTable\" border=\"0\" width=\"530\" style=\"display: inline; border: solid 1px #7FAAFF; background-color: #C5D9FF; padding: 2px;margin-top:8px;\">\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\t\r\n");
      out.write("  </body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
