/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2016-01-28 01:42:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.wx.pay;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;
import java.util.*;

public final class wxpay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String context = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+context+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>微信支付</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(context);
      out.write("/js/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    \r\n");
      out.write("     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"");
      out.print(context);
      out.write("/js/bootstrap/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"");
      out.print(context);
      out.write("/js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t    <script language=\"javascript\" src=\"");
      out.print(context);
      out.write("/js/qq/jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"UTF-8\" src=\"");
      out.print(context);
      out.write("/js/qq/jweixin-1.0.0.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write(" <body class=\"container\">\r\n");
      out.write(" <h3 align=\"center\" class=\"h3\">交易订单</h3>\r\n");
      out.write(" <form   role=\"form\">\r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("    <label for=\"orderNo\" class=\"h4\">商家订单号: </label><input id=\"orderNo\" type=\"text\"    class=\"form-control\"value=\"");
      out.print(request.getParameter("orderNo"));
      out.write("\" disabled=\"disabled\" />\r\n");
      out.write("   <label  for=\"body\" class=\"h4\">商品名称:</label><input id=\"body\" type=\"text\"  class=\"form-control\" value=\"");
      out.print(new String(request.getParameter("body").getBytes("ISO-8859-1"),"utf-8") );
      out.write("\"  disabled=\"disabled\" />\r\n");
      out.write("    <label for=\"money\" class=\"h4\">商品金额:</label><input id=\"money\" type=\"text\"  class=\"form-control\" value=\"");
      out.print(request.getParameter("money"));
      out.write("\" disabled=\"disabled\" />\r\n");
      out.write("   </div>\r\n");
      out.write("   <div style=\"text-align:center;size:100px;\">\r\n");
      out.write("   <button type=\"button\" class=\"btn btn-success save_submit\" onclick=\"callpay()\">确定支付 </button>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("   <button type=\"button\" class=\"btn btn-warning\" onclick=\"backOrg()\" >返回购物 </button>\r\n");
      out.write("   </div>\r\n");
      out.write("</form>\r\n");
      out.write("  </body >\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \tfunction callpay(){\r\n");
      out.write("\t\t WeixinJSBridge.invoke('getBrandWCPayRequest',{\r\n");
      out.write("  \t\t \"appId\" : \"");
      out.print(request.getParameter("appid"));
      out.write("\",\r\n");
      out.write("  \t\t \"timeStamp\" : \"");
      out.print(request.getParameter("timeStamp"));
      out.write("\", \r\n");
      out.write("  \t\t \"nonceStr\" : \"");
      out.print(request.getParameter("nonceStr"));
      out.write("\", \r\n");
      out.write("  \t\t \"package\" : \"");
      out.print(request.getParameter("package"));
      out.write("\",\r\n");
      out.write("  \t\t \"signType\" : \"");
      out.print(request.getParameter("signType"));
      out.write("\", \r\n");
      out.write("  \t\t \"paySign\" : \"");
      out.print(request.getParameter("sign"));
      out.write("\" \r\n");
      out.write("   \t\t\t},function(res){\r\n");
      out.write("\t\t\t\tWeixinJSBridge.log(res.err_msg);\r\n");
      out.write("\t            if(res.err_msg == \"get_brand_wcpay_request:ok\"){  \r\n");
      out.write("\t            \talert(\"支付成功!\");\r\n");
      out.write("\t            }else if(res.err_msg == \"get_brand_wcpay_request:cancel\"){  \r\n");
      out.write("\t                alert(\"用户取消支付!\");  \r\n");
      out.write("\t            }else{  \r\n");
      out.write("\t                alert(\"支付失败!\"+res.err_msg);  \r\n");
      out.write("\t            }  \r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t};\r\n");
      out.write("  </script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \tfunction backOrg(){\r\n");
      out.write("  \t\tvar orderNo=\"");
      out.print(request.getParameter("orderNo"));
      out.write("\";\r\n");
      out.write("  \t\tif(orderNo){\r\n");
      out.write("  \t\t\twindow.location.href=\"");
      out.print(context);
      out.write("/backservlet?orderNo=\"+orderNo;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t}\r\n");
      out.write("  </script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
